# Generated by Django 6.0 on 2026-01-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('horse_power', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('average', 'Average')], default='good', max_length=50)),
                ('price_per_hour', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('jcb', 'JCB'), ('trolley', 'Trolley')], default='tractor', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tractors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tractor')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/')),
                ('is_included', models.BooleanField(default=True)),
                ('extra_price', models.IntegerField(blank=True, null=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.tractor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tractor')),
            ],
        ),
    ]
