# Generated by Django 6.0 on 2026-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='password',
        ),
        migrations.AddField(
            model_name='owner',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
