# Generated by Django 6.0 on 2026-01-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_owner_password_owner_otp_owner_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tractor',
            old_name='horse_power',
            new_name='horsepower',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_included',
        ),
        migrations.AddField(
            model_name='equipment',
            name='price_per_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tractor',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractors', to='core.owner'),
        ),
    ]
