# Generated by Django 6.0 on 2026-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_horse_power_tractor_horsepower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tractor',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='insured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tractor',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tractor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tractor',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tractor',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tractor',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='price_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
