# Generated by Django 6.0 on 2026-02-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_completed_at_owner_location_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
